var hours = ['6am','7am', '8am', '9am', '10am', '11am', '12pm', '1pm', '2pm', '3pm', '4pm', '5pm', '6pm', '7pm'];


/* Below is a list of all the different sites as objects and their methods that are needed to get the information for each */

var firstAndPike = {
  location : '1st and Pike',
  sales : {
    minCust : 23,
    maxCust : 65,
    averageCookie : 6.3,
    hourlyCookies : []
  },
  //generates a random number based on the stores parameters for the number of cookies for an hour
  simulatedCookiesPerHour : function(){
    return(Math.ceil((Math.random() * (this.sales.maxCust - this.sales.minCust) + this.sales.minCust) * this.sales.averageCookie));
  },
  //this will generate and populate the hourly cookies.  This uses random information generated by the simulated cookies per hour function which then gets piushed to the hourly cookies array!
  calculateCookiesPerHour : function(){
    var numOfHours = hours.length;
    for(var i = 0; i < numOfHours; i++){
      this.sales.hourlyCookies.push(this.simulatedCookiesPerHour());
    }
  }
};

var seaTacAirport = {
  location : 'SeaTac Airport',
  sales : {
    minCust : 3,
    maxCust : 24,
    averageCookie : 1.2,
    hourlyCookies : []
  },
  //generates a random number based on the stores parameters for the number of cookies for an hour
  simulatedCookiesPerHour : function(){
    return(Math.ceil((Math.random() * (this.sales.maxCust - this.sales.minCust) + this.sales.minCust) * this.sales.averageCookie));
  },
  //this will generate and populate the hourly cookies.  This uses random information generated by the simulated cookies per hour function which then gets piushed to the hourly cookies array!
  calculateCookiesPerHour : function(){
    var numOfHours = hours.length;
    for(var i = 0; i < numOfHours; i++){
      this.sales.hourlyCookies.push(this.simulatedCookiesPerHour());
    }
  }
};

var seattleCenter = {
  location : 'Seattle Center',
  sales : {
    minCust : 11,
    maxCust : 38,
    averageCookie : 3.7,
    hourlyCookies : []
  },
  //generates a random number based on the stores parameters for the number of cookies for an hour
  simulatedCookiesPerHour : function(){
    return(Math.ceil((Math.random() * (this.sales.maxCust - this.sales.minCust) + this.sales.minCust) * this.sales.averageCookie));
  },
  //this will generate and populate the hourly cookies.  This uses random information generated by the simulated cookies per hour function which then gets piushed to the hourly cookies array!
  calculateCookiesPerHour : function(){
    var numOfHours = hours.length;
    for(var i = 0; i < numOfHours; i++){
      this.sales.hourlyCookies.push(this.simulatedCookiesPerHour());
    }
  }
};

var capitolHill = {
  location : 'Capitol Hill',
  sales : {
    minCust : 20,
    maxCust : 38,
    averageCookie : 2.3,
    hourlyCookies : []
  },
  //generates a random number based on the stores parameters for the number of cookies for an hour
  simulatedCookiesPerHour : function(){
    return(Math.ceil((Math.random() * (this.sales.maxCust - this.sales.minCust) + this.sales.minCust) * this.sales.averageCookie));
  },
  //this will generate and populate the hourly cookies.  This uses random information generated by the simulated cookies per hour function which then gets piushed to the hourly cookies array!
  calculateCookiesPerHour : function(){
    var numOfHours = hours.length;
    for(var i = 0; i < numOfHours; i++){
      this.sales.hourlyCookies.push(this.simulatedCookiesPerHour());
    }
  }
};

var alki = {
  location : 'Alki',
  sales : {
    minCust : 2,
    maxCust : 16,
    averageCookie : 4.6,
    hourlyCookies : []
  },
  //generates a random number based on the stores parameters for the number of cookies for an hour
  simulatedCookiesPerHour : function(){
    return(Math.ceil((Math.random() * (this.sales.maxCust - this.sales.minCust) + this.sales.minCust) * this.sales.averageCookie));
  },
  //this will generate and populate the hourly cookies.  This uses random information generated by the simulated cookies per hour function which then gets piushed to the hourly cookies array!
  calculateCookiesPerHour : function(){
    var numOfHours = hours.length;
    for(var i = 0; i < numOfHours; i++){
      this.sales.hourlyCookies.push(this.simulatedCookiesPerHour());
    }
  }
};

var stores = [];
stores.push(firstAndPike, seaTacAirport, seattleCenter, capitolHill, alki);
var numStores = stores.length;
//test stuff
stores.forEach(function(store){
  store.calculateCookiesPerHour();
  console.log('Results: ' + store.sales.hourlyCookies);
});

