'use strict';

var hours = ['6am','7am', '8am', '9am', '10am', '11am', '12pm', '1pm', '2pm', '3pm', '4pm', '5pm', '6pm', '7pm'];

//this is our 'database' that would hold all of the data needed to create the basic objects

var storeInformation = [
  {storeLocation : '1st and Pike', minCust : 23, maxCust: 65, averageCookie : 6.3},
  {storeLocation : 'SeaTac Airport', minCust : 3, maxCust : 24, averageCookie : 1.2},
  {storeLocation : 'Seattle Center', minCust : 11, maxCust : 38, averageCookie : 3.7},
  {storeLocation : 'Capitol Hill', minCust : 20, maxCust : 38, averageCookie : 2.3},
  {storeLocation : 'Alki', minCust : 2, maxCust : 16, averageCookie : 4.6}
];

console.log(storeInformation);
/* Below is a list of all the different sites as objects and their methods that are needed to get the information for each */

//Build contructor
function StoreConstructor(storeLocation, minCust, maxCust, averageCookie) {
  this.storeLocation = storeLocation;
  this.sales = {
    minCust : minCust,
    maxCust : maxCust,
    averageCookie : averageCookie,
    hourlyCookies : []
  };
  //generates a random number based on the stores parameters for the number of cookies for an hour
  this.simulatedCookiesPerHour = function(){
    return(Math.ceil((Math.random() * (this.sales.maxCust - this.sales.minCust) + this.sales.minCust) * this.sales.averageCookie));
  };
  //this will generate and populate the hourly cookies.  This uses random information generated by the simulated cookies per hour function which then gets piushed to the hourly cookies array!
  this.calculateCookiesPerHour = function(){
    var numOfHours = hours.length;
    for(var i = 0; i < numOfHours; i++){
      this.sales.hourlyCookies.push(this.simulatedCookiesPerHour());
    }
  };
}

//Create the stores array and create each individual store and put the information in there
var stores = [];
storeInformation.forEach(function(singleStoreInfo){
  //create store object using constructor
  var newStore = new StoreConstructor(singleStoreInfo['storeLocation'], singleStoreInfo['minCust'], singleStoreInfo['maxCust'], singleStoreInfo['averageCookie']);
  console.log(newStore);
  //add new store to list
  stores.push(newStore);
});
console.log('PRINT ARRAY OF OBJECTS');
console.log(stores);



//This function is for the ID's it converts the normal string of the location into an HTML acceptable string for an ID
function hyphenize(strToHyphenize){
  strToHyphenize = 'store-' + strToHyphenize; //this will take care of nunbers being the stores name
  strToHyphenize = strToHyphenize.replace(/ /g, '-');
  console.log(strToHyphenize);
  return strToHyphenize;
}


// OLD COLD BELOW //

//This for loop goes through each store and does 2 things, populates the numbers for the cookies
//As well as creates the appropriate HTML for storing the data into different ULs
stores.forEach(function(store){
  store.calculateCookiesPerHour();
  console.log('Results: ' + store.sales.hourlyCookies);
  //gets the salesStuff element in the code
  var bodyEL = document.getElementById('salesStuff');
  //creates 2 elements a P tag for the name of the location and a UL for that specific p tag
  var pEL = document.createElement('p');
  var ulEL = document.createElement('ul');
  //this sets the ID of the UL to the stores name for getting that ID for writing LI later
  ulEL.id = hyphenize(store.location);
  //write the store name into the P tag
  pEL.textContent = store.location;
  //Appends these items to the DOM
  pEL.appendChild(ulEL);
  bodyEL.appendChild(pEL);
});

//This function actually puts the information into the auto generated HTML from the previous loop
stores.forEach(function(store){
  //gets the elements that we want to add into by name as initiates the variables
  var ulEl = document.getElementById(hyphenize(store.location));
  var numOfHours = store.sales.hourlyCookies.length;
  var totalCookies = 0;
  //This loop adds into all the list items to the underorder list
  for (var i = 0; i < numOfHours; i++) {
    // create a <li> element
    var liEl = document.createElement('li');
    // give it content
    liEl.textContent = hours[i] + ': ' + store.sales.hourlyCookies[i] + ' Cookies';
    // put it in the DOM
    ulEl.appendChild(liEl);
    // keep running total
    totalCookies += store.sales.hourlyCookies[i];
  }
  //last line addition for total
  liEl = document.createElement('li');
  liEl.textContent = 'Total: ' + totalCookies;
  ulEl.appendChild(liEl);
});
